name: Publish new version of documentation
on:
  repository_dispatch:
    types:
      - push-tag
      
  workflow_dispatch:
  
jobs:
  publish_docs:
    name: Publish tagged documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout Framework
        with:
          repository: qooxdoo/qooxdoo
          ref: ${{ github.event.client_payload.ref }}
          path: 'qooxdoo'
      - uses: actions/checkout@v2
        name: Checkout published docs
        with:
          ref: gh-pages
          path: 'documentation'
          
      - id: get_dest_dir
        run: |
          ref=${{ github.event.client_payload.ref }}
          dir=$(echo "$ref" | cut -d / -f 3 | cut -d . -f 1-2)
          echo "::set-output name=destination_dir::$dir"
          echo "destination dir is ${{ steps.get_dest_dir.outputs.destination_dir }}"

      - name: Deploy to GH page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./qooxdoo/docs
          destination_dir: ${{ steps.get_dest_dir.outputs.destination_dir }}


